import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.containerWrapper}>
      <Head>
        <title>Test Grid - Search Complex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <section className={styles.feedback}>feedback block</section>
        <section className={styles.searchBox}>
          Search Box <input />
        </section>
        <section className={styles.guide}>Guide Block</section>
        <section className={styles.verts}>Verticals</section>
        <aside className={styles.filters}>Side Bar with Filters</aside>
        <main className={styles.results}>Search results</main>
        <section className={styles.paging}>Pagination</section>
      </div>
    </div>
  );
};

export default Home;
